name: CI

on: 
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

permissions: 
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - name: Install AppMap tools
      id: install-appmap
      uses: getappmap/install-action@v1
      with:
        project-type: npm
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "ci: Add AppMap language agent and appmap.yml"
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
    # Begin AppMap bootstrap archive step
    - name: Archive AppMaps
      id: appmap-bootstrap-archive-appmaps
      uses: getappmap/archive-action@v1
      with:
        revision: ${{ github.event.pull_request.base.sha }}
    # End AppMap bootstrap archive step
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
    - name: Lint
      run: npm run lint
    - name: Publish
      run: npm publish
    - name: Cleanup
      run: npm prune --production
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist