name: CI

on: [push]

permissions: 
  # Allows the EndBug/add-and-commit step to commit the package manager changes,
  # adding the AppMap language library and configuration file appmap.yml.
  # Once the EndBug/add-and-commit is removed, this permission can be removed, 
  # unless you need it for other reasons.
  contents: write

  # Allows the getappmap/archive-action to write a PR comment with the 
  # AppMap configuration status.
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    # Begin AppMap CI language agent installation
    # This snippet can be safely removed once the AppMap language agent has been
    # added to the project dependencies, and appmap.yml has been created.
    - name: Install AppMap tools
      id: install-appmap
      uses: getappmap/install-action@v1
      with:
        project-type: npm
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "ci: Add AppMap language agent and appmap.yml"
    # End AppMap CI language agent installation
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
    - name: Lint
      run: npm run lint
    - name: Publish
      run: npm publish
    - name: Cleanup
      run: npm prune --production
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist