name: Main Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test-access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Permissions
        run: |
          echo "Testing repository access and permissions."
          ls -la .github/workflows
